name: Deploy WPOven Plugin Docs via SFTP

on:
  push:
    branches:
      - main  # Change as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Specify the Node.js version you need

      - name: Install Dependencies & Build
        run: |
          cd wpoven_docs
          ls
          npm install
          npm run build

      - name: Deploy via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          source: "wpoven_docs/build"
          target: "/public_html/docs_html"

