name: Deploy WPOven Plugin Docs via SFTP

on:
  push:
    branches:
      - main  # Change as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Specify the Node.js version you need

      - name: Install Dependencies & Build
        run: |
          cd wpoven_docs
          ls
          npm install
          npm run build

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.SFTP_HOST }}
          ftp-username: ${{ secrets.SFTP_USER }}
          ftp-password: ${{ secrets.SFTP_PASS }}
          ftp-password: "wpoven_docs/build/"
          server-dir: "/public_html/docs_html"

